
/*******************************************************************
*
* CAUTION: This file is automatically generated by HSI.
* Version: 2023.1
* DO NOT EDIT.
*
* Copyright (C) 2010-2024 Xilinx, Inc. All Rights Reserved.
* SPDX-License-Identifier: MIT 

* 
* Description: Driver configuration
*
*******************************************************************/

#include "xhwicap.h"

/*
* The configuration table for devices
*/

XHwIcap_Config XHwIcap_ConfigTable[1] =
{
	{
		0, //XPAR_PERIPHERALS_AXI_HWICAP_0_DEVICE_ID,
		0, //XPAR_PERIPHERALS_AXI_HWICAP_0_BASEADDR,
		0, //XPAR_PERIPHERALS_AXI_HWICAP_0_ICAP_DWIDTH,
		0, //XPAR_PERIPHERALS_AXI_HWICAP_0_MODE
	}
};


